// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.hardware.camera2.CameraCaptureSession$StateCallback
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_hardware_camera2_CameraCaptureSession_StateCallback extends android.hardware.camera2.CameraCaptureSession.StateCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_hardware_camera2_CameraCaptureSession_StateCallback(String key) {
        super();
        this.key_ = key;
        Log.d(TAG, "[Adapter_android_hardware_camera2_CameraCaptureSession_StateCallback] created key=" + key);
    }

    @Override
    public void onConfigured(android.hardware.camera2.CameraCaptureSession arg0) {
        Log.d(TAG, "[Adapter_android_hardware_camera2_CameraCaptureSession_StateCallback] onConfigured key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onConfigured", new Object[]{ arg0 });
    }

    @Override
    public void onConfigureFailed(android.hardware.camera2.CameraCaptureSession arg0) {
        Log.d(TAG, "[Adapter_android_hardware_camera2_CameraCaptureSession_StateCallback] onConfigureFailed key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onConfigureFailed", new Object[]{ arg0 });
    }

    @Override
    public String toString() {
        return "Adapter_android_hardware_camera2_CameraCaptureSession_StateCallback[key=" + key_ + "]";
    }

}
