// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.hardware.camera2.CameraDevice$StateCallback
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;
import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_hardware_camera2_CameraDevice_StateCallback extends android.hardware.camera2.CameraDevice.StateCallback {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_hardware_camera2_CameraDevice_StateCallback(String key) {
        super();
        this.key_ = key;
        Log.d(TAG, "[Adapter_android_hardware_camera2_CameraDevice_StateCallback] created key=" + key);
    }

    @Override
    public void onOpened(android.hardware.camera2.CameraDevice arg0) {
        Log.d(TAG, "[Adapter_android_hardware_camera2_CameraDevice_StateCallback] onOpened key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onOpened", new Object[]{ arg0 });
    }

    @Override
    public void onDisconnected(android.hardware.camera2.CameraDevice arg0) {
        Log.d(TAG, "[Adapter_android_hardware_camera2_CameraDevice_StateCallback] onDisconnected key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
            key_, "onDisconnected", new Object[]{ arg0 });
    }

    @Override
    public void onError(android.hardware.camera2.CameraDevice arg0, int arg1) {
        Log.d(TAG, "[Adapter_android_hardware_camera2_CameraDevice_StateCallback] onError key=" + key_ + " params=2");
        StratumInvocationHandler.nativeDispatch(
            key_, "onError", new Object[]{ arg0, Integer.valueOf(arg1) });
    }

    @Override
    public String toString() {
        return "Adapter_android_hardware_camera2_CameraDevice_StateCallback[key=" + key_ + "]";
    }

}
