// Auto-generated by Stratum Stage 05.5 — DO NOT EDIT
// Source: android.view.TextureView$SurfaceTextureListener
// Copy this file to: runtime/java/com/stratum/adapters/
package com.stratum.adapters;

import android.util.Log;

import com.stratum.runtime.StratumInvocationHandler;

public class Adapter_android_view_TextureView_SurfaceTextureListener implements android.view.TextureView.SurfaceTextureListener {

    private static final String TAG = "StratumAdapter";
    private final String key_;

    public Adapter_android_view_TextureView_SurfaceTextureListener(String key) {
        this.key_ = key;
        Log.d(TAG, "[Adapter_android_view_TextureView_SurfaceTextureListener] created key=" + key);
    }

    @Override
    public void onSurfaceTextureAvailable(android.graphics.SurfaceTexture arg0, int arg1, int arg2) {
        Log.d(TAG, "[Adapter_android_view_TextureView_SurfaceTextureListener] onSurfaceTextureAvailable key=" + key_ + " params=3");
        StratumInvocationHandler.nativeDispatch(
                key_, "onSurfaceTextureAvailable", new Object[]{arg0, Integer.valueOf(arg1), Integer.valueOf(arg2)});
    }

    @Override
    public void onSurfaceTextureSizeChanged(android.graphics.SurfaceTexture arg0, int arg1, int arg2) {
        Log.d(TAG, "[Adapter_android_view_TextureView_SurfaceTextureListener] onSurfaceTextureSizeChanged key=" + key_ + " params=3");
        StratumInvocationHandler.nativeDispatch(
                key_, "onSurfaceTextureSizeChanged", new Object[]{arg0, Integer.valueOf(arg1), Integer.valueOf(arg2)});
    }

    @Override
    public boolean onSurfaceTextureDestroyed(android.graphics.SurfaceTexture arg0) {
        Log.d(TAG, "[Adapter_android_view_TextureView_SurfaceTextureListener] onSurfaceTextureDestroyed key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
                key_, "onSurfaceTextureDestroyed", new Object[]{arg0});
        return false;
    }

    @Override
    public void onSurfaceTextureUpdated(android.graphics.SurfaceTexture arg0) {
        Log.d(TAG, "[Adapter_android_view_TextureView_SurfaceTextureListener] onSurfaceTextureUpdated key=" + key_ + " params=1");
        StratumInvocationHandler.nativeDispatch(
                key_, "onSurfaceTextureUpdated", new Object[]{arg0});
    }

    @Override
    public String toString() {
        return "Adapter_android_view_TextureView_SurfaceTextureListener[key=" + key_ + "]";
    }

}
